[workspace]
members = [
    "integration-tests",
    "node",
    "pallets/commitments",
    "pallets/subtensor",
    "runtime",
]
resolver = "2"

[profile.release]
panic = "unwind"

[profile.test]
opt-level = 3
