[workspace]
members = [
    "integration-tests",
    "node",
    "pallets/subtensor",
    "pallets/commitments",
    "runtime",
]
resolver = "2"

[profile.release]
panic = "unwind"

[profile.test]
opt-level = 3

[workspace.lints.clippy]
indexing_slicing = { level = "deny", priority = 2 } # Direct indexing can lead to panics
