[package]
name = "integration-tests"
version = "0.0.1"
description = "Tracks integration tests for Opentensor substrate node"
authors = ["S0AndS0 <https://github.com/S0AndS0>"]
edition = "2021"
license = "Unlicense"
repository = "https://github.com/opentensor/subtensor"

[lints]
workspace = true
